### PR TITLE
fix: #333 get rke2_node_name for only hosts in current cluster inventory group

### LINKED ISSUE #333: bug: etcd restore failing on getting rke2_node_name
### Summary

When i try to restore newly deployed cluster from s3 backup task that gathers all rke2_node_name from inventories is failing. In debug mode i can see that vars are gathered also from localhost which is not using this variable since it is not in `rke2_cluster_group_name` which in my case is `k8s_cluster`. I am setting all rke2 setting in `group_vars/k8s_cluster/rke2.yaml` so `group_vars/all/main.yaml` files has no rke2 settings at all.

The related task is here: to https://github.com/lablabs/ansible-role-rke2/blob/602b420a9536724e066206b691f4b5292af39b24/tasks/first_server.yml#L169-L173

### Issue Type

Bug Report

### Ansible Version

```console
ansible [core 2.17.12]
  config file = /Users/michal/platform-infra/ansible/ansible.cfg
  configured module search path = ['/Users/michal/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/michal/.pyenv/versions/3.13.3/envs/platform/lib/python3.13/site-packages/ansible
  ansible collection location = /Users/michal/.ansible/collections:/usr/share/ansible/collections:/Users/michal/platform-infra/ansible/collections
  executable location = /Users/michal/.pyenv/versions/platform/bin/ansible
  python version = 3.13.3 (main, May  5 2025, 13:28:27) [Clang 17.0.0 (clang-1700.0.13.3)] (/Users/michal/.pyenv/versions/3.13.3/envs/platform/bin/python)
  jinja version = 3.1.6
  libyaml = True
```

### Steps to Reproduce

backup etcd (to s3 or local), provision new nodes, configure restore parameters and use previous backup with playbook

### Expected Results

Module gathers all current inventory node names from `rke2_cluster_group_name` group

### Actual Results

```console
15:44:12  TASK [lablabs.rke2 : Get all node names] ***************************************
15:44:16  fatal: [dev-02-node01]: FAILED! => 
15:44:16    msg: |-
15:44:16      The task includes an option with an undefined variable. The error was: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'rke2_node_name'. 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'rke2_node_name'
```

### PR DESCRIPTION
**Pull request by michalg91**
# Description
This fixes #333 

- The problem was in extracting hostvars by set_fact method which handled all hosts in inventory
- `register: node_names` registered ansible_fact dict so next steps in this block execution were comparing list to dict so were triggered when not needed
```
{'ansible_facts': {'node_names': ['node01', 'node02,  'node03']]}, 'failed': False, 'changed': False}
```

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Small minor change not affecting the Ansible Role code (GitHub Actions Workflow, Documentation etc.)

## How Has This Been Tested?
Created clean nodes and set credentials for s3 restore, then run playbook which invoked role.

### CODE REVIEW

**Comment by michalg91** [comment]
i encountered another problem (since this one encountered for me when i bumped role from 1.37.0 to 1.44.1)
i have automatic jenkins pipeline that restores cluster in daily manner, it brakes when joinining worker nodes now. 

https://github.com/lablabs/ansible-role-rke2/commit/e43df6b7c98e22ec1a796cf1796b4b6b6612338f this commit totally changed logic, so right after my "fix" it is not executed anymore since all hostnames have the same name in my backup scenario. 

@simonfelding do you remember why this logic is changed? i am able to fix it but i need to know what was the case here so my change will not produce any other failures.

**Comment by simonfelding** [comment]
Hey, would love to help you out on this. Could you give us a bit more info on what exactly doesn't work? It's not entirely clear for me what it is your pipeline is doing and what the error is.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by michalg91** [comment]
Yeah, sure.
It works like that:
1. Login to control-plane node, trigger `rke2 etcd-snapshot save --name xxx`
2. Generates restore variables for role
3. Destroying cluster on **vmware** with `terraform destroy`
4. Recreates fresh nodes from same terraform definitions `terraform apply` (so here all node names are same like previous)
5. Runs `ansible-rke2-role` with provided restore settings

As i mentioned in issue, firstly it was broken in gathering `rke2_node_name` because it also tried to find `rke2_node_name` in other not related to `k8s_cluster` group hosts
https://github.com/lablabs/ansible-role-rke2/blob/602b420a9536724e066206b691f4b5292af39b24/tasks/first_server.yml#L169-L173
so i changed it to find in k8s cluster group, also removed register part because it causes to return dict instead of list of hosts. So diff always happened and it removed all my nodes secrets (also with fresh first master node).

After "my" change the step with removing "unwanted secrets" is skipped because no diff exists (which is true, all my nodes have same name as before destroy).

What i meant with changed logic. In 1.37.0 restore removed all nodes secrets in kube-system, but skipped master so playbook was working fine. Right now it tries to diff `kubectl get node` output with **ansible inventory nodes**. So in my case it is skipping deletion of old secrets and when node is joining to cluster it will not join because it has missmatched credentials `Node password rejected, duplicate hostname or contents of '/etc/rancher/node/password'`.

To fix this i think we should reintroduce previous version in just this step (deleting secrets) so all existing secrets instead currents playbook node will be deleted. The next step with deleting not existing nodes is fine for me with differential check.

**Comment by michalg91** [comment]
https://github.com/lablabs/ansible-role-rke2/pull/334/commits/7518ec55c09f9672409fca1a8e94757921e577d8

this change fixed all my problems

**Comment by michalg91** [comment]
no @simonfelding i run some debug and output hostvars, the problem is what i stated and explained. When i am using inventory file with not only kubernetes hosts or running any play which invoked localhost before invoking role. It will not found `rke2_node_name` on host that is not part of cluster group. Just check it yourself :). Use `rke2_node_name` only in `k8s_cluster` group and debug this line by piping it to `ansible.builtin.debug`, with any any other host outside this group. 

Deleting secrets is not working with current version because it checks for difference with inventory file and kubectl output. In my case host names didn't change (there is no difference). So when playbook was joining reporovisioned nodes they missmatched rke2 credentials. So this step must delete old secrets - Just like before https://github.com/lablabs/ansible-role-rke2/commit/e43df6b7c98e22ec1a796cf1796b4b6b6612338f this commit. Also when you registered same variable name as fact name it dumps dict instead of list so after your commit difference always existed falsely.

Of course this can be also checked in debug.

Check it out.

put this inside debug.yaml to role
```yaml debug
 - name: Restore etcd
   when:
    - inventory_hostname == groups[rke2_servers_group_name].0
   block:
    - name: Get registered nodes
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          {{ rke2_data_path }}/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml \
          get nodes --no-headers | awk '{print $1}'
      args:
        executable: /bin/bash
      changed_when: false
      register: registered_node_names

    - name: Get all node names
      ansible.builtin.set_fact:
        node_names: "{{ hostvars | dict2items | map(attribute='value.rke2_node_name') }}"
      run_once: true 
      register: node_names 

    - name: Remove old <node>.node-password.rke2 secrets
      ansible.builtin.debug: 
        msg: |
          {{ rke2_data_path }}/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml \
          delete secret {{ item }}.node-password.rke2 -n kube-system 2>&1 || true
      # args:
      #   executable: /bin/bash
      with_items: "{{ registered_node_names.stdout_lines | difference(node_names) }}"
      changed_when: false

    - name: Remove old nodes
      ansible.builtin.debug:
        msg: |
          {{ rke2_data_path }}/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml \
          delete node {{ item }} 2>&1 || true
      # args:
      #   executable: /bin/bash
      with_items: "{{ registered_node_names.stdout_lines | difference(node_names) }}"
      changed_when: false

    - name: variables
      ansible.builtin.debug:
        msg: |
          stdout
          {{ registered_node_names.stdout_lines }}

          node_names
          {{ node_names }}

          diffed
          {{ registered_node_names.stdout_lines | difference(node_names) }}

          diffed with node name
          {{ registered_node_names.stdout_lines | difference([rke2_node_name]) }}
```

and run:
```
- name: debug
  tags: debug
  gather_facts: yes
  become: yes
  hosts: k8s_cluster
  tasks:
    - ansible.builtin.include_role:
        name: lablabs.rke2
        tasks_from: debug
```

all in all recreating new cluster with etcd snapshot should delete all previously existed secrets so new joined node can join cluster.

**Comment by simonfelding** [comment]
>all in all recreating new cluster with etcd snapshot should delete all previously existed secrets so new joined node can join cluster.

This is the part I'm worried about - is that always the case, or is that only in your case? You could also have a situation where you need to recover the etcd snapshot because etcd failed for some reason, but you didn't delete the nodes.

I'm not 100% sure why [rke2 uses the node-passwords like that, but maybe it's a security feature](https://docs.rke2.io/advanced#how-agent-node-registration-works)? I think we shouldn't just delete all the secrets just because etcd is being restored. 

https://github.com/lablabs/ansible-role-rke2/blob/602b420a9536724e066206b691f4b5292af39b24/tasks/first_server.yml#L171
It looks to me like the problem is actually just that line 171 assumes all hosts are rke2 nodes - which is why your localhost was included `"{{ hostvars | dict2items | map(attribute='value.rke2_node_name') }}"`.

Isn't the solution just to change it to `"{{ hostvars[groups['rke2_servers_group_name']] | dict2items | map(attribute='value.rke2_node_name') }}"`?

**Comment by simonfelding** [comment]
Actually, the entire block Is misplaced.
https://github.com/lablabs/ansible-role-rke2/blob/602b420a9536724e066206b691f4b5292af39b24/tasks/first_server.yml#L155C1-L193C1

It doesn't do what it says it does (restore etcd), as this was already done earlier in the file. It actually deletes nodes that are no longer present in the ansible inventory.

I think this block belongs in the beginning of the `remaining_nodes.yml` file, to make it clear that it's a matter of removing nodes that aren't in the ansible inventory. It's not directly related to restoring etcd.
